"""Adiciona fabricante e modelo ao ativo

Revision ID: 2c1cef108f3f
Revises: 
Create Date: 2026-07-01 11:33:50.267207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1cef108f3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabricante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('modelo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.drop_column('modelo')
        batch_op.drop_column('fabricante')

    # ### end Alembic commands ###
